name: test3

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * 1-5"

jobs:
  build

    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Download and mod fenix
      run: |
        wget -q -O "resp32m" https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.nightly.latest.arm64-v8a/artifacts/public/build/armeabi-v7a/target.apk
        wget -q -O "resp64m" https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.nightly.latest.arm64-v8a/artifacts/public/build/arm64-v8a/target.apk
        wget -q https://github.com/iBotPeaches/Apktool/releases/download/v2.5.0/apktool_2.5.0.jar
        
        java -jar apktool_2.5.0.jar d resp32m -o v7a
        java -jar apktool_2.5.0.jar d resp64m -o v8a
        ls -h
